services:
  - type: worker
    name: hadith-bot
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HADITH_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true