services:
  - type: worker
    name: hadith-bot
    env: docker
    region: frankfurt
    plan: free
    branch: main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HADITH_API_KEY
        sync: false
    autoDeploy: true